\set ON_ERROR_STOP on

-- Canonical market-data v2 hard cutover.
--
-- Run with backend, workers, and paper runtimes stopped. Take a schema-only and
-- data backup before execution. This migration intentionally creates no dual
-- writes, compatibility views, or runtime fallback path.

SELECT (
    to_regclass('legacy_market_v1.market_candles_raw') IS NOT NULL
    AND to_regclass('market.candle_versions') IS NOT NULL
    AND to_regclass('public.market_candles_raw') IS NULL
) AS market_data_v2_complete
\gset

\if :market_data_v2_complete
DO $$
BEGIN
    IF to_regclass('public.derivatives_market_state') IS NOT NULL
       OR to_regclass('public.portal_candle_closures') IS NOT NULL THEN
        RAISE EXCEPTION
            'market_data_v2_repeat_invalid: legacy active tables remain in public';
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM legacy_market_v1.migration_manifest
        WHERE migration_id = 'market_data_v2_hard_cutover'
          AND completed_at IS NOT NULL
    ) THEN
        RAISE EXCEPTION
            'market_data_v2_repeat_invalid: completed manifest is missing';
    END IF;
END;
$$;
\echo 'market_data_v2_hard_cutover already complete; verification passed'
SELECT *
FROM legacy_market_v1.migration_manifest
WHERE migration_id = 'market_data_v2_hard_cutover';
\quit
\endif

BEGIN;
SELECT pg_advisory_xact_lock(9021002);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
DECLARE
    missing_instruments bigint;
    invalid_rows bigint;
    open_rows bigint;
    invalid_source_times bigint;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
        RAISE EXCEPTION 'market_data_v2_preflight: timescaledb extension is required';
    END IF;
    IF to_regclass('public.market_candles_raw') IS NULL THEN
        RAISE EXCEPTION 'market_data_v2_preflight: public.market_candles_raw is missing';
    END IF;
    IF to_regclass('market.candle_versions') IS NOT NULL
       OR to_regclass('legacy_market_v1.market_candles_raw') IS NOT NULL THEN
        RAISE EXCEPTION
            'market_data_v2_preflight: partial canonical or archive state exists';
    END IF;

    SELECT count(*) INTO missing_instruments
    FROM public.market_candles_raw AS candle
    LEFT JOIN public.portal_instruments AS instrument
      ON instrument.id = candle.instrument_id
    WHERE instrument.id IS NULL
       OR NULLIF(btrim(instrument.datasource), '') IS NULL;
    IF missing_instruments > 0 THEN
        RAISE EXCEPTION
            'market_data_v2_preflight: % candle rows lack a canonical instrument/provider',
            missing_instruments;
    END IF;

    SELECT count(*) INTO invalid_rows
    FROM public.market_candles_raw
    WHERE close_time <= candle_time
       OR high < low
       OR high < open
       OR high < close
       OR low > open
       OR low > close
       OR volume < 0
       OR trade_count < 0
       OR timeframe_seconds <= 0;
    IF invalid_rows > 0 THEN
        RAISE EXCEPTION
            'market_data_v2_preflight: % malformed candle rows', invalid_rows;
    END IF;

    SELECT count(*) INTO open_rows
    FROM public.market_candles_raw
    WHERE NOT is_closed;
    IF open_rows > 0 THEN
        RAISE EXCEPTION
            'market_data_v2_preflight: % provisional candles cannot enter canonical storage',
            open_rows;
    END IF;

    SELECT count(*) INTO invalid_source_times
    FROM public.market_candles_raw
    WHERE source_time IS NOT NULL AND source_time < close_time;
    IF invalid_source_times > 0 THEN
        RAISE EXCEPTION
            'market_data_v2_preflight: % source timestamps precede candle close',
            invalid_source_times;
    END IF;
END;
$$;

CREATE SCHEMA market;
CREATE SCHEMA legacy_market_v1;

CREATE TABLE market.sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key varchar(64) NOT NULL,
    provider varchar(64) NOT NULL,
    venue varchar(128) NOT NULL DEFAULT '',
    source_kind varchar(32) NOT NULL,
    adapter_version varchar(128) NOT NULL,
    lineage jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_market_sources_identity_key UNIQUE (identity_key),
    CONSTRAINT ck_market_sources_provider CHECK (provider <> ''),
    CONSTRAINT ck_market_sources_kind CHECK (source_kind <> ''),
    CONSTRAINT ck_market_sources_adapter_version CHECK (adapter_version <> '')
);

CREATE TABLE market.series (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key varchar(64) NOT NULL,
    instrument_id varchar(64) NOT NULL REFERENCES public.portal_instruments(id) ON DELETE RESTRICT,
    fact_type varchar(64) NOT NULL,
    timeframe_seconds integer,
    contract_version varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_market_series_identity_key UNIQUE (identity_key),
    CONSTRAINT ck_market_series_fact_type CHECK (fact_type <> ''),
    CONSTRAINT ck_market_series_timeframe_positive
        CHECK (timeframe_seconds IS NULL OR timeframe_seconds > 0),
    CONSTRAINT ck_market_series_candle_timeframe
        CHECK (fact_type <> 'candle.ohlcv' OR timeframe_seconds IS NOT NULL)
);
CREATE INDEX ix_market_series_instrument_fact
    ON market.series (instrument_id, fact_type);

CREATE TABLE market.ingestion_runs (
    id varchar(64) PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES market.sources(id) ON DELETE RESTRICT,
    status varchar(16) NOT NULL,
    request jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_revision varchar(128),
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    requested_start timestamptz,
    requested_end timestamptz,
    requested_count integer NOT NULL DEFAULT 0,
    inserted_count integer NOT NULL DEFAULT 0,
    corrected_count integer NOT NULL DEFAULT 0,
    noop_count integer NOT NULL DEFAULT 0,
    error text,
    CONSTRAINT ck_market_ingestion_runs_status
        CHECK (status IN ('running', 'completed', 'failed')),
    CONSTRAINT ck_market_ingestion_requested_count CHECK (requested_count >= 0),
    CONSTRAINT ck_market_ingestion_inserted_count CHECK (inserted_count >= 0),
    CONSTRAINT ck_market_ingestion_corrected_count CHECK (corrected_count >= 0),
    CONSTRAINT ck_market_ingestion_noop_count CHECK (noop_count >= 0)
);
CREATE INDEX ix_market_ingestion_runs_source_started
    ON market.ingestion_runs (source_id, started_at);

CREATE TABLE market.candle_versions (
    series_id bigint NOT NULL REFERENCES market.series(id) ON DELETE RESTRICT,
    candle_open_time timestamptz NOT NULL,
    revision integer NOT NULL,
    market_commit_seq bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    ingestion_run_id varchar(64) NOT NULL
        REFERENCES market.ingestion_runs(id) ON DELETE RESTRICT,
    candle_close_time timestamptz NOT NULL,
    open double precision NOT NULL,
    high double precision NOT NULL,
    low double precision NOT NULL,
    close double precision NOT NULL,
    volume double precision,
    trade_count bigint,
    source_published_at timestamptz,
    received_at timestamptz,
    accepted_at timestamptz NOT NULL,
    known_at timestamptz NOT NULL,
    known_at_method varchar(64) NOT NULL,
    provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
    row_hash varchar(64) NOT NULL,
    CONSTRAINT pk_market_candle_versions
        PRIMARY KEY (series_id, candle_open_time, revision),
    CONSTRAINT ck_market_candle_revision_positive CHECK (revision > 0),
    CONSTRAINT ck_market_candle_time_order CHECK (candle_close_time > candle_open_time),
    CONSTRAINT ck_market_candle_high_low CHECK (high >= low),
    CONSTRAINT ck_market_candle_high_bounds CHECK (high >= open AND high >= close),
    CONSTRAINT ck_market_candle_low_bounds CHECK (low <= open AND low <= close),
    CONSTRAINT ck_market_candle_volume CHECK (volume IS NULL OR volume >= 0),
    CONSTRAINT ck_market_candle_trade_count CHECK (trade_count IS NULL OR trade_count >= 0),
    CONSTRAINT ck_market_candle_known_after_close CHECK (known_at >= candle_close_time),
    CONSTRAINT ck_market_candle_known_after_publication
        CHECK (source_published_at IS NULL OR known_at >= source_published_at),
    CONSTRAINT ck_market_candle_receipt_order
        CHECK (received_at IS NULL OR (known_at >= received_at AND accepted_at >= received_at))
);

SELECT create_hypertable(
    'market.candle_versions',
    by_range('candle_open_time'),
    if_not_exists => TRUE,
    migrate_data => TRUE
);
CREATE INDEX ix_market_candle_versions_series_time_revision
    ON market.candle_versions (series_id, candle_open_time DESC, revision DESC);
CREATE INDEX ix_market_candle_versions_series_commit
    ON market.candle_versions (series_id, market_commit_seq);
CREATE INDEX ix_market_candle_versions_series_known
    ON market.candle_versions (series_id, known_at);

CREATE TABLE market.gap_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id bigint NOT NULL REFERENCES market.series(id) ON DELETE RESTRICT,
    ingestion_run_id varchar(64) REFERENCES market.ingestion_runs(id) ON DELETE RESTRICT,
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    classification varchar(64) NOT NULL,
    expected_count integer NOT NULL DEFAULT 0,
    observed_count integer NOT NULL DEFAULT 0,
    detected_as_of_commit_seq bigint NOT NULL,
    evidence_hash varchar(64) NOT NULL,
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_market_gap_time_order CHECK (end_time > start_time),
    CONSTRAINT ck_market_gap_expected_count CHECK (expected_count >= 0),
    CONSTRAINT ck_market_gap_observed_count CHECK (observed_count >= 0),
    CONSTRAINT uq_market_gap_evidence
        UNIQUE (series_id, start_time, end_time, evidence_hash)
);
CREATE INDEX ix_market_gap_evidence_series_window
    ON market.gap_evidence (series_id, start_time, end_time);

CREATE TABLE market.datasets (
    id varchar(64) PRIMARY KEY,
    dataset_hash varchar(64) NOT NULL,
    name varchar(255),
    purpose varchar(64) NOT NULL DEFAULT 'research',
    max_commit_seq bigint NOT NULL,
    created_by varchar(128),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_market_datasets_hash UNIQUE (dataset_hash),
    CONSTRAINT ck_market_dataset_commit_seq CHECK (max_commit_seq >= 0)
);

CREATE TABLE market.dataset_series (
    dataset_id varchar(64) NOT NULL REFERENCES market.datasets(id) ON DELETE RESTRICT,
    series_id bigint NOT NULL REFERENCES market.series(id) ON DELETE RESTRICT,
    range_start timestamptz NOT NULL,
    range_end timestamptz NOT NULL,
    max_commit_seq bigint NOT NULL,
    row_count integer NOT NULL,
    material_hash varchar(64) NOT NULL,
    provenance_hash varchar(64) NOT NULL,
    source_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    quality_hash varchar(64) NOT NULL,
    quality_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_market_dataset_series
        PRIMARY KEY (dataset_id, series_id, range_start, range_end),
    CONSTRAINT ck_market_dataset_series_range CHECK (range_end > range_start),
    CONSTRAINT ck_market_dataset_series_commit_seq CHECK (max_commit_seq >= 0),
    CONSTRAINT ck_market_dataset_series_row_count CHECK (row_count >= 0)
);
CREATE INDEX ix_market_dataset_series_series
    ON market.dataset_series (series_id, range_start, range_end);

CREATE FUNCTION pg_temp.sha256_text(payload text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT encode(digest(convert_to(payload, 'UTF8'), 'sha256'), 'hex')
$$;

CREATE FUNCTION pg_temp.json_string(payload text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT to_json(payload)::text
$$;

CREATE FUNCTION pg_temp.canonical_time(payload timestamptz)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT to_char(
        payload AT TIME ZONE 'UTC',
        'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'
    )
$$;

CREATE FUNCTION pg_temp.canonical_float(payload double precision)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT encode(
        float8send(CASE WHEN payload = 0 THEN 0::double precision ELSE payload END),
        'hex'
    )
$$;

CREATE FUNCTION pg_temp.source_identity_key(
    provider text,
    venue text,
    source_kind text,
    adapter_version text
)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT pg_temp.sha256_text(
        '{"adapter_version":' || pg_temp.json_string(adapter_version) ||
        ',"provider":' || pg_temp.json_string(lower(provider)) ||
        ',"source_kind":' || pg_temp.json_string(lower(source_kind)) ||
        ',"venue":' || pg_temp.json_string(lower(venue)) ||
        '}'
    )
$$;

CREATE FUNCTION pg_temp.series_identity_key(
    instrument_id text,
    fact_type text,
    timeframe_seconds integer,
    contract_version text
)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT pg_temp.sha256_text(
        '{"contract_version":' || pg_temp.json_string(contract_version) ||
        ',"fact_type":' || pg_temp.json_string(fact_type) ||
        ',"instrument_id":' || pg_temp.json_string(instrument_id) ||
        ',"schema_version":"market_series.v1"' ||
        ',"timeframe_seconds":' || timeframe_seconds::text ||
        '}'
    )
$$;

CREATE FUNCTION pg_temp.candle_row_hash(
    candle_open_time timestamptz,
    candle_close_time timestamptz,
    open_value double precision,
    high_value double precision,
    low_value double precision,
    close_value double precision,
    volume_value double precision,
    trade_count_value bigint,
    source_published_at_value timestamptz,
    received_at_value timestamptz,
    known_at_value timestamptz,
    known_at_method_value text
)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT pg_temp.sha256_text(
        '{"close":' || pg_temp.json_string(pg_temp.canonical_float(close_value)) ||
        ',"close_time":' || pg_temp.json_string(pg_temp.canonical_time(candle_close_time)) ||
        ',"high":' || pg_temp.json_string(pg_temp.canonical_float(high_value)) ||
        ',"known_at":' || pg_temp.json_string(pg_temp.canonical_time(known_at_value)) ||
        ',"known_at_method":' || pg_temp.json_string(known_at_method_value) ||
        ',"low":' || pg_temp.json_string(pg_temp.canonical_float(low_value)) ||
        ',"open":' || pg_temp.json_string(pg_temp.canonical_float(open_value)) ||
        ',"open_time":' || pg_temp.json_string(pg_temp.canonical_time(candle_open_time)) ||
        ',"received_at":' || COALESCE(
            pg_temp.json_string(pg_temp.canonical_time(received_at_value)), 'null'
        ) ||
        ',"schema_version":"candle.ohlcv.v1"' ||
        ',"source_published_at":' || COALESCE(
            pg_temp.json_string(pg_temp.canonical_time(source_published_at_value)), 'null'
        ) ||
        ',"trade_count":' || COALESCE(trade_count_value::text, 'null') ||
        ',"volume":' || COALESCE(
            pg_temp.json_string(pg_temp.canonical_float(volume_value)), 'null'
        ) ||
        '}'
    )
$$;

INSERT INTO market.sources (
    identity_key, provider, venue, source_kind, adapter_version, lineage
)
SELECT DISTINCT
    pg_temp.source_identity_key(
        instrument.datasource,
        COALESCE(instrument.exchange, ''),
        'legacy_import',
        'legacy_market_v1'
    ),
    instrument.datasource,
    COALESCE(instrument.exchange, ''),
    'legacy_import',
    'legacy_market_v1',
    jsonb_build_object(
        'schema_version', 'market_source_lineage.v1',
        'legacy_table', 'public.market_candles_raw',
        'known_at_policy', 'source_time_or_interval_close'
    )
FROM public.market_candles_raw AS candle
JOIN public.portal_instruments AS instrument
  ON instrument.id = candle.instrument_id;

INSERT INTO market.series (
    identity_key, instrument_id, fact_type, timeframe_seconds, contract_version
)
SELECT DISTINCT
    pg_temp.series_identity_key(
        candle.instrument_id,
        'candle.ohlcv',
        candle.timeframe_seconds,
        'candle.ohlcv.v1'
    ),
    candle.instrument_id,
    'candle.ohlcv',
    candle.timeframe_seconds,
    'candle.ohlcv.v1'
FROM public.market_candles_raw AS candle;

INSERT INTO market.ingestion_runs (
    id, source_id, status, request, source_revision,
    requested_start, requested_end, requested_count
)
SELECT
    'legacy_v1_' || source.id::text,
    source.id,
    'running',
    jsonb_build_object(
        'schema_version', 'market_ingestion_request.v1',
        'operation', 'legacy_market_v1_hard_cutover',
        'source_table', 'public.market_candles_raw'
    ),
    'legacy_market_v1',
    min(candle.candle_time),
    max(candle.close_time),
    count(*)::integer
FROM public.market_candles_raw AS candle
JOIN public.portal_instruments AS instrument
  ON instrument.id = candle.instrument_id
JOIN market.sources AS source
  ON source.identity_key = pg_temp.source_identity_key(
      instrument.datasource,
      COALESCE(instrument.exchange, ''),
      'legacy_import',
      'legacy_market_v1'
  )
GROUP BY source.id;

INSERT INTO market.candle_versions (
    series_id, candle_open_time, revision, ingestion_run_id,
    candle_close_time, open, high, low, close, volume, trade_count,
    source_published_at, received_at, accepted_at, known_at,
    known_at_method, provenance, row_hash
)
SELECT
    series.id,
    candle.candle_time,
    1,
    'legacy_v1_' || source.id::text,
    candle.close_time,
    candle.open,
    candle.high,
    candle.low,
    candle.close,
    candle.volume,
    candle.trade_count,
    candle.source_time,
    NULL,
    GREATEST(candle.inserted_at, candle.close_time),
    COALESCE(candle.source_time, candle.close_time),
    CASE
        WHEN candle.source_time IS NOT NULL THEN 'legacy_source_time'
        ELSE 'legacy_interval_close_inferred'
    END,
    jsonb_build_object(
        'legacy_inserted_at', candle.inserted_at,
        'legacy_is_closed', candle.is_closed,
        'legacy_table', 'public.market_candles_raw'
    ),
    pg_temp.candle_row_hash(
        candle.candle_time,
        candle.close_time,
        candle.open,
        candle.high,
        candle.low,
        candle.close,
        candle.volume,
        candle.trade_count,
        candle.source_time,
        NULL,
        COALESCE(candle.source_time, candle.close_time),
        CASE
            WHEN candle.source_time IS NOT NULL THEN 'legacy_source_time'
            ELSE 'legacy_interval_close_inferred'
        END
    )
FROM public.market_candles_raw AS candle
JOIN public.portal_instruments AS instrument
  ON instrument.id = candle.instrument_id
JOIN market.sources AS source
  ON source.identity_key = pg_temp.source_identity_key(
      instrument.datasource,
      COALESCE(instrument.exchange, ''),
      'legacy_import',
      'legacy_market_v1'
  )
JOIN market.series AS series
  ON series.identity_key = pg_temp.series_identity_key(
      candle.instrument_id,
      'candle.ohlcv',
      candle.timeframe_seconds,
      'candle.ohlcv.v1'
  )
ORDER BY series.id, candle.candle_time;

UPDATE market.ingestion_runs AS run
SET status = 'completed',
    finished_at = now(),
    inserted_count = run.requested_count
WHERE run.status = 'running'
  AND run.source_revision = 'legacy_market_v1';

WITH ordered AS (
    SELECT
        series.id AS series_id,
        candle.candle_time,
        candle.timeframe_seconds,
        lag(candle.candle_time) OVER (
            PARTITION BY series.id ORDER BY candle.candle_time
        ) AS previous_time
    FROM public.market_candles_raw AS candle
    JOIN market.series AS series
      ON series.instrument_id = candle.instrument_id
     AND series.timeframe_seconds = candle.timeframe_seconds
     AND series.fact_type = 'candle.ohlcv'
), gaps AS (
    SELECT
        series_id,
        previous_time + make_interval(secs => timeframe_seconds) AS start_time,
        candle_time AS end_time,
        GREATEST(
            floor(extract(epoch FROM (candle_time - previous_time)) / timeframe_seconds)::integer - 1,
            0
        ) AS missing_count
    FROM ordered
    WHERE previous_time IS NOT NULL
      AND candle_time - previous_time > make_interval(secs => timeframe_seconds)
), watermarks AS (
    SELECT series_id, max(market_commit_seq) AS max_commit_seq
    FROM market.candle_versions
    GROUP BY series_id
)
INSERT INTO market.gap_evidence (
    series_id, ingestion_run_id, start_time, end_time, classification,
    expected_count, observed_count, detected_as_of_commit_seq,
    evidence_hash, evidence
)
SELECT
    gap.series_id,
    candle.ingestion_run_id,
    gap.start_time,
    gap.end_time,
    'missing',
    gap.missing_count,
    0,
    watermark.max_commit_seq,
    pg_temp.sha256_text(
        gap.series_id::text || '|' || pg_temp.canonical_time(gap.start_time) ||
        '|' || pg_temp.canonical_time(gap.end_time) || '|missing'
    ),
    jsonb_build_object(
        'schema_version', 'market_gap_evidence.v1',
        'source', 'legacy_market_v1_continuity_scan',
        'limitation', 'internal gaps only; requested outer coverage was not recoverable'
    )
FROM gaps AS gap
JOIN watermarks AS watermark ON watermark.series_id = gap.series_id
JOIN LATERAL (
    SELECT ingestion_run_id
    FROM market.candle_versions
    WHERE series_id = gap.series_id
    ORDER BY candle_open_time
    LIMIT 1
) AS candle ON TRUE;

DO $$
DECLARE
    legacy_count bigint;
    canonical_count bigint;
    mismatch_count bigint;
BEGIN
    SELECT count(*) INTO legacy_count FROM public.market_candles_raw;
    SELECT count(*) INTO canonical_count FROM market.candle_versions WHERE revision = 1;
    IF canonical_count <> legacy_count THEN
        RAISE EXCEPTION
            'market_data_v2_reconcile: count mismatch legacy=% canonical=%',
            legacy_count, canonical_count;
    END IF;

    SELECT count(*) INTO mismatch_count
    FROM public.market_candles_raw AS legacy
    JOIN market.series AS series
      ON series.instrument_id = legacy.instrument_id
     AND series.timeframe_seconds = legacy.timeframe_seconds
     AND series.fact_type = 'candle.ohlcv'
    JOIN market.candle_versions AS canonical
      ON canonical.series_id = series.id
     AND canonical.candle_open_time = legacy.candle_time
     AND canonical.revision = 1
    WHERE canonical.candle_close_time IS DISTINCT FROM legacy.close_time
       OR canonical.open IS DISTINCT FROM legacy.open
       OR canonical.high IS DISTINCT FROM legacy.high
       OR canonical.low IS DISTINCT FROM legacy.low
       OR canonical.close IS DISTINCT FROM legacy.close
       OR canonical.volume IS DISTINCT FROM legacy.volume
       OR canonical.trade_count IS DISTINCT FROM legacy.trade_count
       OR canonical.source_published_at IS DISTINCT FROM legacy.source_time
       OR canonical.known_at IS DISTINCT FROM COALESCE(legacy.source_time, legacy.close_time)
       OR canonical.row_hash IS DISTINCT FROM pg_temp.candle_row_hash(
            legacy.candle_time,
            legacy.close_time,
            legacy.open,
            legacy.high,
            legacy.low,
            legacy.close,
            legacy.volume,
            legacy.trade_count,
            legacy.source_time,
            NULL,
            COALESCE(legacy.source_time, legacy.close_time),
            CASE
                WHEN legacy.source_time IS NOT NULL THEN 'legacy_source_time'
                ELSE 'legacy_interval_close_inferred'
            END
       );
    IF mismatch_count > 0 THEN
        RAISE EXCEPTION
            'market_data_v2_reconcile: % exact value/hash mismatches', mismatch_count;
    END IF;
END;
$$;

ALTER TABLE public.market_candles_raw SET SCHEMA legacy_market_v1;
ALTER TABLE IF EXISTS public.derivatives_market_state SET SCHEMA legacy_market_v1;
ALTER TABLE IF EXISTS public.portal_candle_closures SET SCHEMA legacy_market_v1;

CREATE TABLE legacy_market_v1.migration_manifest (
    migration_id text PRIMARY KEY,
    source_schema_version text NOT NULL,
    target_contract_version text NOT NULL,
    legacy_candle_count bigint NOT NULL,
    canonical_candle_count bigint NOT NULL,
    source_count bigint NOT NULL,
    series_count bigint NOT NULL,
    gap_evidence_count bigint NOT NULL,
    known_at_policy text NOT NULL,
    completed_at timestamptz NOT NULL
);
INSERT INTO legacy_market_v1.migration_manifest (
    migration_id,
    source_schema_version,
    target_contract_version,
    legacy_candle_count,
    canonical_candle_count,
    source_count,
    series_count,
    gap_evidence_count,
    known_at_policy,
    completed_at
)
SELECT
    'market_data_v2_hard_cutover',
    'legacy_market_v1',
    'candle.ohlcv.v1',
    (SELECT count(*) FROM legacy_market_v1.market_candles_raw),
    (SELECT count(*) FROM market.candle_versions),
    (SELECT count(*) FROM market.sources),
    (SELECT count(*) FROM market.series),
    (SELECT count(*) FROM market.gap_evidence),
    'source_time when valid; otherwise interval close inferred',
    now();

CREATE OR REPLACE FUNCTION market.reject_immutable_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'immutable market-data relation %.% rejects %',
        TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP;
END;
$$;

CREATE TRIGGER trg_reject_mutation_sources
BEFORE UPDATE OR DELETE ON market.sources
FOR EACH ROW EXECUTE FUNCTION market.reject_immutable_mutation();
CREATE TRIGGER trg_reject_mutation_series
BEFORE UPDATE OR DELETE ON market.series
FOR EACH ROW EXECUTE FUNCTION market.reject_immutable_mutation();
CREATE TRIGGER trg_reject_mutation_candle_versions
BEFORE UPDATE OR DELETE ON market.candle_versions
FOR EACH ROW EXECUTE FUNCTION market.reject_immutable_mutation();
CREATE TRIGGER trg_reject_mutation_gap_evidence
BEFORE UPDATE OR DELETE ON market.gap_evidence
FOR EACH ROW EXECUTE FUNCTION market.reject_immutable_mutation();
CREATE TRIGGER trg_reject_mutation_datasets
BEFORE UPDATE OR DELETE ON market.datasets
FOR EACH ROW EXECUTE FUNCTION market.reject_immutable_mutation();
CREATE TRIGGER trg_reject_mutation_dataset_series
BEFORE UPDATE OR DELETE ON market.dataset_series
FOR EACH ROW EXECUTE FUNCTION market.reject_immutable_mutation();

COMMIT;

SELECT *
FROM legacy_market_v1.migration_manifest
WHERE migration_id = 'market_data_v2_hard_cutover';
