#!/usr/bin/env python3
"""Render the immutable SQL seed from QT's canonical Fact registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from market_data.fact_registry import supported_static_fact_payload_schemas


def _sql_text(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_registry_seed() -> str:
    rows: list[str] = []
    for schema in supported_static_fact_payload_schemas():
        contract = json.dumps(
            schema.contract,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
        )
        query_fields = json.dumps(list(schema.query_fields), separators=(",", ":"))
        rows.append(
            "(\n"
            f"    {_sql_text(schema.schema_id)},\n"
            f"    {_sql_text(schema.fact_type)},\n"
            f"    {_sql_text(schema.contract_hash)},\n"
            f"    $fact_contract${contract}$fact_contract$::jsonb,\n"
            f"    {_sql_text(schema.observation_time_field)},\n"
            f"    {_sql_text(schema.material_hash_version)},\n"
            f"    {_sql_text(schema.row_hash_version)},\n"
            f"    {_sql_text(query_fields)}::jsonb,\n"
            f"    {'true' if schema.dataset_eligible else 'false'}\n"
            ")"
        )
    return (
        "-- Generated by scripts/db/render_canonical_fact_registry.py.\n"
        "-- Edit src/market_data/fact_registry.py, then regenerate this file.\n\n"
        "INSERT INTO market.fact_schemas (\n"
        "    schema_id, fact_type, contract_hash, contract,\n"
        "    observation_time_field, material_hash_version, row_hash_version,\n"
        "    query_fields, dataset_eligible\n"
        ")\nVALUES\n"
        + ",\n".join(rows)
        + "\nON CONFLICT (schema_id) DO NOTHING;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_registry_seed()
    if args.output is None:
        print(rendered, end="")
        return 0
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(
                "canonical_fact_registry_seed_stale: "
                f"run scripts/db/render_canonical_fact_registry.py --output {args.output}"
            )
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
