"""Minimal order routing engine with deterministic simulation fills."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Callable, Dict, List, Optional, Tuple

from core.logger import logger

Side = str


@dataclass
class ExecutionRequest:
    """Represents a trading intent emitted by a strategy box."""

    correlation_id: str
    strategy_id: str
    symbol: str
    side: Side
    qty: float
    timestamp: datetime
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if isinstance(self.timestamp, datetime) and self.timestamp.tzinfo is None:
            self.timestamp = self.timestamp.replace(tzinfo=timezone.utc)
        self.side = self.side.lower()


@dataclass
class OrderRecord:
    """Internal representation of an accepted order."""

    order_id: str
    request: ExecutionRequest
    created_at: datetime
    status: str


@dataclass
class ExecutionReport:
    """Fill information generated by the broker simulation."""

    order_id: str
    symbol: str
    side: Side
    filled_qty: float
    fill_price: float
    timestamp: datetime


@dataclass
class OrderResponse:
    """Synchronous response returned to the strategy."""

    status: str
    reason: Optional[str] = None
    order_id: Optional[str] = None


class SimBroker:
    """Simple deterministic broker that fills at next open with slippage."""

    def __init__(
        self,
        next_open_lookup: Callable[[str, datetime], Tuple[datetime, float]],
        slippage_bps: float = 0.0,
    ) -> None:
        self._next_open_lookup = next_open_lookup
        self._slippage_bps = slippage_bps

    def execute(self, order: OrderRecord) -> ExecutionReport:
        """Fill the order on the next available open."""

        next_bar = self._next_open_lookup(order.request.symbol, order.request.timestamp)
        if not next_bar:
            raise ValueError("next open price unavailable for symbol")

        next_ts, next_open = next_bar
        slip_multiplier = self._slippage_adjustment(order.request.side)
        fill_price = next_open * slip_multiplier
        fill_ts = next_ts
        return ExecutionReport(
            order_id=order.order_id,
            symbol=order.request.symbol,
            side=order.request.side,
            filled_qty=order.request.qty,
            fill_price=fill_price,
            timestamp=fill_ts,
        )

    def _slippage_adjustment(self, side: Side) -> float:
        bps = self._slippage_bps / 10_000.0
        if side in {"buy", "long"}:
            return 1 + bps
        return 1 - bps


class OrderEngine:
    """Central chokepoint validating orders and dispatching fills."""

    def __init__(
        self,
        broker: SimBroker,
        per_strategy_position_limit: Dict[str, float] | float = float("inf"),
        symbol_exposure_limit: Dict[str, float] | float = float("inf"),
    ) -> None:
        self._broker = broker
        self._per_strategy_limit = per_strategy_position_limit
        self._symbol_limit = symbol_exposure_limit
        self._idempotency: Dict[str, OrderResponse] = {}
        self._accepted_orders: Dict[str, str] = {}
        self._orders: Dict[str, OrderRecord] = {}
        self._executions: List[ExecutionReport] = []
        self._positions: Dict[Tuple[str, str], float] = {}
        self._symbol_positions: Dict[str, float] = {}
        self._sequence = 0

    def submit(self, request: ExecutionRequest) -> OrderResponse:
        """Validate and route an execution request."""

        logger.debug(
            "order_engine.submit", extra={
                "correlation_id": request.correlation_id,
                "strategy_id": request.strategy_id,
                "symbol": request.symbol,
                "side": request.side,
                "qty": request.qty,
            }
        )

        if request.correlation_id in self._accepted_orders:
            order_id = self._accepted_orders[request.correlation_id]
            logger.info(
                "duplicate execution request rejected",
                extra={
                    "correlation_id": request.correlation_id,
                    "strategy_id": request.strategy_id,
                    "order_id": order_id,
                },
            )
            return OrderResponse(status="rejected", reason="duplicate", order_id=order_id)

        if request.correlation_id in self._idempotency:
            logger.info(
                "duplicate execution request reusing rejection",
                extra={"correlation_id": request.correlation_id, "strategy_id": request.strategy_id},
            )
            return self._idempotency[request.correlation_id]

        rejection_reason = self._validate(request)
        if rejection_reason:
            response = OrderResponse(status="rejected", reason=rejection_reason)
            self._idempotency[request.correlation_id] = response
            return response

        order = self._create_order(request)
        response = OrderResponse(status="accepted", order_id=order.order_id)
        self._accepted_orders[request.correlation_id] = order.order_id

        try:
            report = self._broker.execute(order)
        except Exception as exc:  # pragma: no cover - defensive logging
            logger.exception("broker execution failed", extra={"order_id": order.order_id})
            response = OrderResponse(status="rejected", reason=str(exc))
            self._idempotency[request.correlation_id] = response
            return response

        self._register_execution(report)
        return response

    def get_recent_orders(self, limit: int = 20) -> List[OrderRecord]:
        """Return the most recent orders for monitoring endpoints."""

        return sorted(self._orders.values(), key=lambda o: o.created_at, reverse=True)[:limit]

    def get_positions(self) -> Dict[Tuple[str, str], float]:
        """Return the current net position per strategy and symbol."""

        return dict(self._positions)

    def get_symbol_exposure(self) -> Dict[str, float]:
        """Return aggregate symbol exposure across strategies."""

        return dict(self._symbol_positions)

    def get_executions(self) -> List[ExecutionReport]:
        """Return stored execution reports."""

        return list(self._executions)

    # ------------------------------------------------------------------ #
    # Internal helpers                                                   #
    # ------------------------------------------------------------------ #
    def _create_order(self, request: ExecutionRequest) -> OrderRecord:
        self._sequence += 1
        order_id = f"ORD-{self._sequence:06d}"
        order = OrderRecord(
            order_id=order_id,
            request=request,
            created_at=datetime.now(timezone.utc),
            status="accepted",
        )
        self._orders[order_id] = order
        logger.info(
            "order accepted",
            extra={"order_id": order_id, "correlation_id": request.correlation_id, "strategy_id": request.strategy_id},
        )
        return order

    def _validate(self, request: ExecutionRequest) -> Optional[str]:
        if request.qty <= 0:
            logger.warning(
                "order rejected: invalid quantity",
                extra={"correlation_id": request.correlation_id, "qty": request.qty},
            )
            return "quantity must be positive"

        if request.side not in {"buy", "sell", "long", "short"}:
            logger.warning(
                "order rejected: invalid side",
                extra={"correlation_id": request.correlation_id, "side": request.side},
            )
            return "invalid side"

        projected_strategy = self._project_strategy_position(request)
        limit = self._resolve_limit(self._per_strategy_limit, request.strategy_id)
        if abs(projected_strategy) > limit:
            logger.warning(
                "order rejected: strategy position limit",
                extra={
                    "strategy_id": request.strategy_id,
                    "projected_position": projected_strategy,
                    "limit": limit,
                },
            )
            return "strategy position limit"

        projected_symbol = self._project_symbol_position(request)
        symbol_limit = self._resolve_limit(self._symbol_limit, request.symbol)
        if abs(projected_symbol) > symbol_limit:
            logger.warning(
                "order rejected: symbol exposure limit",
                extra={"symbol": request.symbol, "projected_exposure": projected_symbol, "limit": symbol_limit},
            )
            return "symbol exposure limit"

        return None

    def _resolve_limit(self, cfg: Dict[str, float] | float, key: str) -> float:
        if isinstance(cfg, dict):
            return cfg.get(key, float("inf"))
        return cfg

    def _project_strategy_position(self, request: ExecutionRequest) -> float:
        current = self._positions.get((request.strategy_id, request.symbol), 0.0)
        delta = request.qty if request.side in {"buy", "long"} else -request.qty
        return current + delta

    def _project_symbol_position(self, request: ExecutionRequest) -> float:
        current = self._symbol_positions.get(request.symbol, 0.0)
        delta = request.qty if request.side in {"buy", "long"} else -request.qty
        return current + delta

    def _register_execution(self, report: ExecutionReport) -> None:
        self._executions.append(report)
        strategy_key = None
        if report.order_id in self._orders:
            order = self._orders[report.order_id]
            strategy_key = (order.request.strategy_id, order.request.symbol)
            delta = report.filled_qty if report.side in {"buy", "long"} else -report.filled_qty
            self._positions[strategy_key] = self._positions.get(strategy_key, 0.0) + delta
            self._symbol_positions[order.request.symbol] = self._symbol_positions.get(order.request.symbol, 0.0) + delta

        logger.info(
            "execution recorded",
            extra={
                "order_id": report.order_id,
                "strategy_key": strategy_key,
                "filled_qty": report.filled_qty,
                "fill_price": report.fill_price,
            },
        )
