#!/usr/bin/env python3
"""Build component index for architecture docs based on frontmatter tags."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARCH_DIR = ROOT / "docs" / "architecture"
INDEX_PATH = ARCH_DIR / "ARCHITECTURE_COMPONENT_INDEX.md"


def _parse_frontmatter(path: Path) -> dict[str, str | list[str]]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    data: dict[str, str | list[str]] = {}
    current_key: str | None = None
    for line in lines[1:]:
        stripped = line.strip()
        if stripped == "---":
            break
        if not stripped:
            continue
        if stripped.startswith("- ") and current_key:
            data.setdefault(current_key, [])
            assert isinstance(data[current_key], list)
            data[current_key].append(stripped[2:].strip())
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value:
            data[key] = value
            current_key = None
        else:
            data[key] = []
            current_key = key
    return data


def _as_list(value: str | list[str] | None) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value]
    return [str(value)]


def main() -> int:
    entries: list[dict[str, object]] = []
    for path in sorted(ARCH_DIR.glob("*.md")):
        if path.name == INDEX_PATH.name:
            continue
        meta = _parse_frontmatter(path)
        if not meta:
            continue
        entries.append(
            {
                "path": path,
                "component": str(meta.get("component", "unknown")),
                "subsystem": str(meta.get("subsystem", "unknown")),
                "layer": str(meta.get("layer", "unknown")),
                "tags": _as_list(meta.get("tags")),
                "code_paths": _as_list(meta.get("code_paths")),
                "status": str(meta.get("status", "unknown")),
            }
        )

    lines: list[str] = []
    lines.append("# Architecture Component Index")
    lines.append("")
    lines.append("Generated by `python scripts/docs/build_architecture_index.py`.")
    lines.append("")
    lines.append("## Components")
    lines.append("")
    lines.append("| Component | Subsystem | Layer | Status | Doc |")
    lines.append("|---|---|---|---|---|")
    for entry in sorted(entries, key=lambda item: (str(item["subsystem"]), str(item["component"]))):
        path = Path(entry["path"]).relative_to(ROOT)
        lines.append(
            f"| {entry['component']} | {entry['subsystem']} | {entry['layer']} | {entry['status']} | [{path.name}]({path.as_posix()}) |"
        )

    lines.append("")
    lines.append("## Code Path Coverage")
    lines.append("")
    lines.append("| Code Path | Component | Doc |")
    lines.append("|---|---|---|")
    for entry in sorted(entries, key=lambda item: str(item["component"])):
        path = Path(entry["path"]).relative_to(ROOT)
        for code_path in entry["code_paths"]:
            lines.append(f"| `{code_path}` | {entry['component']} | [{path.name}]({path.as_posix()}) |")

    lines.append("")
    lines.append("## Tag Coverage")
    lines.append("")
    lines.append("| Tag | Components |")
    lines.append("|---|---|")
    tag_map: dict[str, set[str]] = {}
    for entry in entries:
        for tag in entry["tags"]:
            tag_map.setdefault(tag, set()).add(str(entry["component"]))
    for tag in sorted(tag_map):
        components = ", ".join(sorted(tag_map[tag]))
        lines.append(f"| `{tag}` | {components} |")

    INDEX_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(ROOT)} with {len(entries)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
