"""Read-only descriptions of registered methods; normalizers remain authoritative."""
from __future__ import annotations

from copy import deepcopy
from typing import Any

from .forward_risk_evaluator import PINNED_PARAMS
from .registry import CHECK_REGISTRY, DURABLE_EVIDENCE_CHECK_FAMILIES, normalize_check_request

SCHEMA = "research_check_catalog.v1"

# Documentation examples only. Replace resource bindings with authorized server IDs.
_EXAMPLES = {'event_fact_analysis@4': {'check_family': 'event_fact_analysis',
                           'scope': {'indicator_id': 'indicator-1',
                                     'instrument_id': 'instrument-1',
                                     'timeframe': '1h',
                                     'start': '2022-01-01T00:00:00Z',
                                     'end': '2022-01-02T00:00:00Z'},
                           'detector': {'type': 'indicator_event',
                                        'output_name': 'atr_expansion',
                                        'event_keys': [{'key': 'atr_expansion_long',
                                                        'direction': 'long'}]},
                           'outcomes': {'horizons': [1, 3]},
                           'inputs': [{'alias': 'reference_price',
                                       'fact_type': 'market.reference_price',
                                       'contract_version': 'market.reference_price.v1',
                                       'dimensions': {'quote_currency': 'USD'},
                                       'source_policy': {'mode': 'exact',
                                                         'source_identity_key': 'source-a'}}],
                           'gap_policy': 'reject',
                           'mode': 'preview'},
 'event_fact_analysis@5': {'check_family': 'event_fact_analysis',
                           'scope': {'indicator_id': 'indicator-1',
                                     'instrument_id': 'instrument-1',
                                     'timeframe': '1h',
                                     'start': '2022-01-01T00:00:00Z',
                                     'end': '2022-01-02T00:00:00Z'},
                           'detector': {'type': 'fact_snapshot',
                                        'input_alias': 'bbo',
                                        'evaluation_trigger': 'required_facts_available'},
                           'outcomes': {'horizons': [1, 3]},
                           'inputs': [{'alias': 'bbo',
                                       'fact_type': 'market.bbo',
                                       'contract_version': 'market.bbo.v1',
                                       'timeframe_seconds': 1,
                                       'max_staleness_seconds': 120,
                                       'source_policy': {'mode': 'exact', 'source_identity_key': 'source-identity-id'}}],
                           'gap_policy': 'reject',
                           'mode': 'preview'},
 'event_fact_analysis@6': {'check_family': 'event_fact_analysis',
                           'mode': 'preview',
                           'inputs': [],
                           'gap_policy': 'reject',
                           'scope': {'indicator_id': 'profile-1',
                                     'instrument_id': 'instrument-1',
                                     'timeframe': '1h',
                                     'start': '2022-01-01T00:00:00+00:00',
                                     'end': '2022-01-01T06:00:00+00:00'},
                           'detector': {'type': 'indicator_event',
                                        'output_name': 'raw',
                                        'event_keys': [{'key': 'raw_long', 'direction': 'long'}]},
                           'outcomes': {'horizons': [1, 2], 'primary_horizon': 2, 'entry_lag_bars': 1},
                           'statistics': {'eligibility': {'min_samples': 1}}},
 'event_fact_analysis@7': {'check_family': 'event_fact_analysis',
                           'mode': 'preview',
                           'inputs': [],
                           'gap_policy': 'reject',
                           'scope': {'indicator_id': 'profile-1',
                                     'instrument_id': 'instrument-1',
                                     'timeframe': '1h',
                                     'start': '2022-01-01T00:00:00+00:00',
                                     'end': '2022-01-01T06:00:00+00:00'},
                           'detector': {'type': 'indicator_event',
                                        'output_name': 'raw',
                                        'event_keys': [{'key': 'raw_long', 'direction': 'long'}]},
                           'outcomes': {'horizons': [1, 2],
                                        'primary_horizon': 2,
                                        'entry_lag_bars': 1,
                                        'matched_origin': {'detector': {'type': 'indicator_event',
                                                                        'output_name': 'confirmed',
                                                                        'event_keys': [{'key': 'confirmed_long',
                                                                                        'direction': 'long'}]},
                                                           'origin_time_path': 'metadata.breakout_time',
                                                           'origin_event_key_path': 'metadata.breakout_event_key',
                                                           'reference_path': 'metadata.reference'}},
                           'statistics': {'eligibility': {'min_samples': 1}}},
 'event_fact_analysis@8': {'check_family': 'event_fact_analysis',
                           'mode': 'preview',
                           'inputs': [],
                           'gap_policy': 'reject',
                           'scope': {'indicator_id': 'profile-1',
                                     'instrument_id': 'instrument-1',
                                     'timeframe': '1h',
                                     'start': '2022-01-01T00:00:00+00:00',
                                     'end': '2022-01-01T06:00:00+00:00'},
                           'detector': {'type': 'indicator_event',
                                        'output_name': 'raw',
                                        'event_keys': [{'key': 'raw_long', 'direction': 'long'}]},
                           'outcomes': {'horizons': [2, 3],
                                        'primary_horizon': 2,
                                        'entry_lag_bars': 1,
                                        'matched_origin': {'detector': {'type': 'indicator_event',
                                                                        'output_name': 'confirmed',
                                                                        'event_keys': [{'key': 'confirmed_long',
                                                                                        'direction': 'long'}]},
                                                           'origin_time_path': 'metadata.breakout_time',
                                                           'origin_event_key_path': 'metadata.breakout_event_key',
                                                           'reference_path': 'metadata.reference'},
                                        'required_horizons': [2, 3],
                                        'shared_landmark': {'classification_lag_bars': 1,
                                                            'sample_lag_bars': 2,
                                                            'readiness_contract': 'market_profile.value_location.v1',
                                                            'dependence': 'leave_one_original_profile_out.v1'}},
                           'statistics': {'eligibility': {'min_samples': 1}}},
 'event_fact_analysis@9': {'check_family': 'event_fact_analysis',
                           'mode': 'preview',
                           'inputs': [],
                           'gap_policy': 'reject',
                           'scope': {'indicator_id': 'profile-1',
                                     'instrument_id': 'instrument-1',
                                     'timeframe': '1h',
                                     'start': '2022-01-01T00:00:00+00:00',
                                     'end': '2022-01-01T06:00:00+00:00'},
                           'detector': {'type': 'indicator_event',
                                        'output_name': 'balance_breakout',
                                        'event_keys': [{'key': 'balance_breakout_long',
                                                        'direction': 'long'}]},
                           'outcomes': {'horizons': [2, 3],
                                        'primary_horizon': 2,
                                        'entry_lag_bars': 1,
                                        'required_horizons': [2],
                                        'first_return': {'classification_lag_bars': 1,
                                                         'sample_lag_bars': 2,
                                                         'readiness_contract': 'market_profile.first_return_state.v2',
                                                         'dependence': 'leave_one_original_profile_out.v1'}},
                           'statistics': {'eligibility': {'min_samples': 1}}},
 'event_fact_analysis@10': {'check_family': 'event_fact_analysis',
                            'mode': 'preview',
                            'inputs': [],
                            'gap_policy': 'reset_rewarm',
                            'scope': {'indicator_id': 'stats-1',
                                      'instrument_id': 'instrument-1',
                                      'timeframe': '1m',
                                      'start': '2022-12-30T00:00:00Z',
                                      'end': '2023-01-01T00:00:00Z',
                                      'warmup_bars': 200},
                            'detector': {'type': 'indicator_event',
                                         'output_name': 'atr_expansion',
                                         'event_keys': [{'key': 'atr_expansion_long',
                                                         'direction': 'long'}]},
                            'outcomes': {'horizon_kind': 'elapsed_time',
                                         'horizons': [1800, 7200, 21600],
                                         'primary_horizon': 7200,
                                         'entry_lag_bars': 0,
                                         'forward_risk': {'schema_version': 'candle_risk_comparison.v1',
                                                          'baseline_bars': 120,
                                                          'readiness_contract': 'candle_stats.public_outputs.v1',
                                                          'outcome_boundary': 'evaluation_end_exclusive'}},
                            'statistics': {}},
 'event_fact_analysis@11': {'check_family': 'event_fact_analysis',
                            'mode': 'preview',
                            'inputs': [],
                            'gap_policy': 'reset_rewarm',
                            'scope': {'indicator_id': 'stats-1',
                                      'instrument_id': 'instrument-1',
                                      'timeframe': '1m',
                                      'start': '2022-12-30T00:00:00Z',
                                      'end': '2023-01-01T00:00:00Z',
                                      'warmup_bars': 200},
                            'detector': {'type': 'indicator_event',
                                         'output_name': 'atr_expansion',
                                         'event_keys': [{'key': 'atr_expansion_long',
                                                         'direction': 'long'}]},
                            'outcomes': {'horizon_kind': 'elapsed_time',
                                         'horizons': [1800, 7200, 21600],
                                         'primary_horizon': 7200,
                                         'entry_lag_bars': 0,
                                         'forward_risk': {'schema_version': 'candle_risk_matched_state.v1',
                                                          'baseline_bars': 120,
                                                          'readiness_contract': 'candle_stats.public_outputs.v1',
                                                          'outcome_boundary': 'evaluation_end_exclusive',
                                                          'matching_contract': 'crossing_state_matched_pairs.v1'}},
                            'statistics': {}},
 'raw_forward_outcome@2': {'check_family': 'raw_forward_outcome',
                           'mode': 'preview',
                           'scope': {'instrument_id': 'instrument-id',
                                     'indicator_id': 'indicator-id',
                                     'timeframe': '1h',
                                     'start': '2022-01-01T00:00:00Z',
                                     'end': '2022-01-02T00:00:00Z'},
                           'detector': {'type': 'raw_condition',
                                        'field': 'close',
                                        'operator': 'gt',
                                        'value_field': 'previous_close'},
                           'outcomes': {'forward_bars': [1, 3]},
                           'gap_policy': 'reject'},
 'indicator_forward_outcome@2': {'check_family': 'indicator_forward_outcome',
                                 'mode': 'preview',
                                 'scope': {'instrument_id': 'instrument-id',
                                           'indicator_id': 'indicator-id',
                                           'timeframe': '1h',
                                           'start': '2022-01-01T00:00:00Z',
                                           'end': '2022-01-02T00:00:00Z'},
                                 'detector': {'type': 'record_match', 'output_name': 'entry'},
                                 'outcomes': {'forward_bars': [1, 3]},
                                 'gap_policy': 'reject'},
 'signal_audit@2': {'check_family': 'signal_audit',
                    'mode': 'preview',
                    'scope': {'instrument_id': 'instrument-id',
                              'indicator_id': 'indicator-id',
                              'timeframe': '1h',
                              'start': '2022-01-01T00:00:00Z',
                              'end': '2022-01-02T00:00:00Z'},
                    'detector': {'type': 'signal_audit',
                                 'source_output': 'state',
                                 'source_field': 'ready',
                                 'signal_output': 'entry',
                                 'event_key': 'entry_long',
                                 'operator': 'eq',
                                 'value': True},
                    'outcomes': {'forward_bars': [1, 3]},
                    'gap_policy': 'reject'},
 'candidate_lifecycle@2': {'check_family': 'candidate_lifecycle',
                           'mode': 'preview',
                           'scope': {'instrument_id': 'instrument-id',
                                     'indicator_id': 'indicator-id',
                                     'timeframe': '1h',
                                     'start': '2022-01-01T00:00:00Z',
                                     'end': '2022-01-02T00:00:00Z'},
                           'detector': {'type': 'candidate_lifecycle'},
                           'outcomes': {'forward_bars': [1, 3]},
                           'gap_policy': 'reject'},
 'run_signal_summary@2': {'check_family': 'run_signal_summary',
                          'mode': 'preview',
                          'scope': {'instrument_id': 'instrument-id',
                                    'indicator_id': 'indicator-id',
                                    'timeframe': '1h',
                                    'start': '2022-01-01T00:00:00Z',
                                    'end': '2022-01-02T00:00:00Z',
                                    'run_id': 'run-id'},
                          'detector': {'type': 'run_signal_match', 'output_name': 'entry'},
                          'outcomes': {'forward_bars': [1, 3]},
                          'gap_policy': 'reject'},
 'run_decision_trade_comparison@2': {'check_family': 'run_decision_trade_comparison',
                                     'mode': 'preview',
                                     'scope': {'instrument_id': 'instrument-id',
                                               'indicator_id': 'indicator-id',
                                               'timeframe': '1h',
                                               'start': '2022-01-01T00:00:00Z',
                                               'end': '2022-01-02T00:00:00Z',
                                               'run_id': 'run-id'},
                                     'detector': {'type': 'run_decision_match',
                                                  'decision_state': 'accepted'},
                                     'outcomes': {'forward_bars': [1, 3]},
                                     'gap_policy': 'reject'}}

_PURPOSES = {
    "raw_forward_outcome@2": "Preview raw candle conditions and subsequent outcomes.",
    "indicator_forward_outcome@2": "Preview indicator output conditions and subsequent outcomes.",
    "signal_audit@2": "Audit emitted signals against declared public output expectations.",
    "candidate_lifecycle@2": "Describe candidate progression and terminal stages.",
    "run_signal_summary@2": "Preview signal evidence from an existing run.",
    "run_decision_trade_comparison@2": "Preview run decisions and linked trade evidence.",
    "event_fact_analysis@3": "Replay the historical indicator-event/typed-Fact method.",
    "event_fact_analysis@4": "Analyze indicator events or Fact snapshots with typed Fact inputs.",
    "event_fact_analysis@5": "Analyze Fact snapshots when required Facts become available.",
    "event_fact_analysis@6": "Describe indicator events using canonical candle-only snapshots.",
    "event_fact_analysis@7": "Attribute follow-up outcomes to exact original indicator events.",
    "event_fact_analysis@8": "Compare original events at a shared classification landmark.",
    "event_fact_analysis@9": "Compare first return to the original market-profile range.",
    "event_fact_analysis@10": "Describe fixed Candle Stats ATR-expansion future risk cohorts.",
    "event_fact_analysis@11": "Compare fixed ATR crossings with matched persistent-high states.",
}


def get_check_definition(definition_id: str, version: str) -> dict[str, Any]:
    """Inspect one registered base version; never select a latest version implicitly."""
    try:
        definition = CHECK_REGISTRY.resolve_definition(definition_id, version)
    except ValueError as exc:
        raise KeyError(f"check_definition_not_found: id={definition_id} version={version}") from exc
    key = f"{definition.definition_id}@{definition.definition_version}"
    if key not in _PURPOSES:
        raise ValueError(f"check_catalog_description_missing: {key}")
    evaluator = CHECK_REGISTRY.resolve_evaluator(definition)
    example = deepcopy(_EXAMPLES.get(key))
    declarations = None
    configured = None
    if example is not None:
        configured, request = normalize_check_request(example)
        if (configured.definition_id != definition.definition_id
                or configured.definition_version.split("+", 1)[0] != definition.definition_version):
            raise ValueError(f"check_catalog_example_version_mismatch: {key}")
        declarations = dict(evaluator.declare_requirements(definition=configured, request=request))
    fixed_risk = definition.definition_id == "event_fact_analysis" and version in {"10", "11"}
    settings = {
        "fixed": deepcopy(dict(definition.material_rules)),
        "configurable": {
            "scope": "Authorized instrument/indicator IDs, timeframe and bounded UTC range supported by this method.",
            "detector": "Only operators/event fields accepted by the existing method normalizer.",
            "outcomes": "Only horizons/outcome fields accepted by the existing method normalizer.",
            "statistics": "Only statistics accepted by the existing method normalizer.",
            "assertions": "Existing scalar assertions; no trading or execution permission.",
        },
        "defaults": {"mode": "preview", "gap_rewarm_bars": 0},
        "constraints": ["Existing request normalizers and requirements/prepare are authoritative.",
                        "Examples are templates, not existing datasets or execution approval."],
    }
    if fixed_risk:
        settings["fixed"].update({
            "indicator_type": "candle_stats", "indicator_parameters": dict(PINNED_PARAMS),
            "timeframe": "1m", "warmup_bars": 200, "gap_policy": "reset_rewarm",
            "detector": deepcopy(example["detector"]), "outcomes": deepcopy(example["outcomes"]),
            "statistics": {},
        })
        settings["configurable"] = {"scope.instrument_id": "Authorized instrument identity.",
                                     "scope.indicator_id": "Existing Candle Stats instance with pinned defaults.",
                                     "scope.start/end": "Aligned UTC range within one calendar year; no outcome tail."}
        settings["constraints"] += ["No configurable inference, matching thresholds or alternate indicators.",
                                     "Descriptive association only; not causality, profitability or promotion."]
        if version == "11":
            settings["fixed"]["matching"] = {"z_caliper": 0.25, "max_prior_rms_ratio": 1.25,
                "calendar_window_days": 7, "primary_horizon_seconds": 7200,
                "control_reuse": False, "same_episode": False,
                "strata": "UTC month x six-hour block x prior RMS bin"}
            settings["constraints"].append("At most 20,000,000 candidate comparisons; result-size and execution budgets still apply.")
    durable = definition.definition_id in DURABLE_EVIDENCE_CHECK_FAMILIES
    return {
        "schema_version": SCHEMA,
        "definition": definition.to_dict(),
        "purpose": _PURPOSES[key],
        "eligibility": {"request_selectable": example is not None,
                        "modes": ["preview", "evidence"] if durable and example is not None else ["preview"] if example is not None else [],
                        "observation": "Requires completed, replayable durable evidence and explicit admission; never automatic." if durable else "Preview only; cannot create new durable evidence or Observations.",
                        "execution_authority": False, "promotion_authority": False},
        "required_inputs": {"declaration": declarations,
                            "evidence_binding": "Exactly one frozen Dataset or supported immutable run evidence; use existing requirements/prepare.",
                            "resource_bindings": {"scope.instrument_id": "Authorized server instrument ID.",
                                                  "scope.indicator_id": "Existing server indicator ID when declared.",
                                                  "inputs[].source_policy": "Authorized source identity/policy for typed inputs.",
                                                  "scope.run_id": "Existing accessible run for run-backed previews."}},
        "settings": settings,
        "result_shape": {"envelope_schema": definition.result_schema_version,
                         "payload_schema": getattr(evaluator, "result_schema_version", "research_check_result.v1"),
                         "envelope_fields": ["definition_hash", "request_hash", "plan_hash", "evidence_hash",
                                             "evaluator_id", "evaluator_version", "result", "result_hash"],
                         "analysis_field": "crossing_state_comparison" if fixed_risk and version == "11" else "forward_risk_comparison" if fixed_risk else None,
                         "meaning": "Bounded analytical output; completed does not certify scientific validity."},
        "examples": [] if example is None else [{"request": example,
                        "configured_definition": configured.to_dict(),
                        "instructions": "Bind resource IDs, then send this request to requirements/prepare. Evidence runs use the returned next_request and Dataset ID."}],
        "compatibility": "Historical replay definition; no current request selects it." if example is None else "Documentation metadata does not change the definition hash or calculation.",
    }


def list_check_definitions() -> dict[str, Any]:
    items = []
    for definition in CHECK_REGISTRY.definitions():
        detail = get_check_definition(definition.definition_id, definition.definition_version)
        items.append({key: detail[key] for key in ("definition", "purpose", "eligibility")})
    return {"schema_version": SCHEMA, "items": items}
