"""Typed-output indicator engine exports."""

from .contracts import (
    DetailDefinition,
    EngineFrame,
    Indicator,
    IndicatorRuntimeSpec,
    OverlayDefinition,
    OutputDefinition,
    OutputRef,
    OutputType,
    RuntimeDetail,
    RuntimeOverlay,
    RuntimeOutput,
    validate_detail_definitions,
    validate_overlay_definitions,
    validate_runtime_detail,
    validate_runtime_overlay,
    validate_output_definitions,
    validate_runtime_output,
)
from .runtime_engine import IndicatorExecutionEngine
from .signal_output import (
    SignalReference,
    SignalOutputEvent,
    assert_signal_output_event,
    assert_signal_output_has_no_execution_fields,
    signal_output_known_at_epoch,
    signal_output_reference,
)

__all__ = [
    "EngineFrame",
    "DetailDefinition",
    "Indicator",
    "IndicatorRuntimeSpec",
    "OverlayDefinition",
    "OutputDefinition",
    "OutputRef",
    "OutputType",
    "RuntimeDetail",
    "RuntimeOverlay",
    "RuntimeOutput",
    "IndicatorExecutionEngine",
    "validate_detail_definitions",
    "validate_overlay_definitions",
    "validate_runtime_detail",
    "validate_runtime_overlay",
    "validate_output_definitions",
    "validate_runtime_output",
    "SignalReference",
    "SignalOutputEvent",
    "assert_signal_output_event",
    "assert_signal_output_has_no_execution_fields",
    "signal_output_known_at_epoch",
    "signal_output_reference",
]
