"""Core execution and domain logic for bot runtime."""

from .domain import (
    CandleSnapshot,
    Candle,
    EntryFill,
    EntryFillResult,
    EntryRequest,
    EntryValidation,
    LadderPosition,
    LadderRiskEngine,
    Leg,
    SameBarResolutionPolicy,
    StrategySignal,
)
from .execution import (
    FillRejection,
    FillResult,
    SpotExecutionConstraints,
    SpotExecutionModel,
    DerivativesExecutionConstraints,
    DerivativesExecutionModel,
)
from .execution_adapter import ExecutionAdapter, SpotExecutionAdapter, DerivativesExecutionAdapter
from .execution_intent import ExecutionIntent, ExecutionOutcome, LimitParams
from .execution_model import ExecutionModel
from .execution_order import (
    FillOrder,
    OrderType,
    build_fill_order,
    execute_fill_order,
)
from .execution_plan import (
    BreakevenPlan,
    EntryExecutionPlan,
    FixedHorizonExitPlan,
    LimitMakerPlan,
    RuntimeExecutionPlan,
    RuntimeStopAdjustment,
    StopAdjustmentPlanRule,
    TrailingStopPlan,
    compile_runtime_execution_plan,
)
from .execution_policy import (
    ExitExecutionPolicy,
    LiquidityRole,
    exit_policy_for,
    fee_rate_for_role,
    normalize_liquidity_role,
)
from .execution_runtime import DeterministicExecutionModel
from .entry_execution import EntryExecutionCoordinator, PendingEntry
from .entry_settlement import EntrySettlement, EntrySettlementContext, EntrySettlementService
from .exit_settlement import ExitSettlement, ExitSettlementContext, ExitSettlementService
from .fees import FeeDetail, FeeResolver, FeeSchedule, executed_fee, executed_notional
from .wallet import (
    LockedWalletLedger,
    WalletEvent,
    WalletLedger,
    WalletState,
    project_wallet,
    project_wallet_from_events,
    wallet_can_apply,
    wallet_can_apply_exit,
    wallet_required_reservation,
    wallet_required_reservation_details,
)
from .wallet_gateway import BaseWalletGateway, SharedWalletGateway, WalletGateway
from .execution_profile import (
    InstrumentContract,
    ExecutionConstraintsContract,
    ExecutionCapabilities,
    ExecutionFeeContract,
    RiskConfigContract,
    CollateralModel,
    SimpleCollateralModel,
    SeriesExecutionProfile,
    normalize_execution_semantics,
    normalize_runtime_instrument_type,
    compile_series_execution_profile,
)
from .runtime_events import (
    DecisionAcceptedContext,
    DecisionRejectedContext,
    SCHEMA_VERSION,
    SignalEmittedContext,
    EntryFilledContext,
    ExitKind,
    ExitFilledContext,
    ReasonCode,
    RuntimeBar,
    RuntimeErrorContext,
    RuntimeEvent,
    RuntimeEventCategory,
    RuntimeStatusContext,
    RuntimeEventName,
    WalletDelta,
    WalletDepositedContext,
    WalletInitializedContext,
    build_correlation_id,
    coerce_reason_code,
    decision_trace_entry_from_runtime_event,
    format_correlation_bar_ts,
    new_runtime_event,
    normalize_utc_datetime,
    runtime_event_from_dict,
)

__all__ = [
    "Candle",
    "CandleSnapshot",
    "EntryFill",
    "EntryFillResult",
    "EntryRequest",
    "EntryValidation",
    "LadderPosition",
    "LadderRiskEngine",
    "Leg",
    "SameBarResolutionPolicy",
    "StrategySignal",
    "FillRejection",
    "FillResult",
    "SpotExecutionConstraints",
    "SpotExecutionModel",
    "DerivativesExecutionConstraints",
    "DerivativesExecutionModel",
    "ExecutionAdapter",
    "SpotExecutionAdapter",
    "DerivativesExecutionAdapter",
    "ExecutionIntent",
    "ExecutionOutcome",
    "LimitParams",
    "ExecutionModel",
    "FillOrder",
    "OrderType",
    "build_fill_order",
    "execute_fill_order",
    "BreakevenPlan",
    "EntryExecutionPlan",
    "FixedHorizonExitPlan",
    "LimitMakerPlan",
    "RuntimeExecutionPlan",
    "RuntimeStopAdjustment",
    "StopAdjustmentPlanRule",
    "TrailingStopPlan",
    "compile_runtime_execution_plan",
    "ExitExecutionPolicy",
    "LiquidityRole",
    "exit_policy_for",
    "fee_rate_for_role",
    "normalize_liquidity_role",
    "DeterministicExecutionModel",
    "EntryExecutionCoordinator",
    "PendingEntry",
    "EntrySettlementService",
    "EntrySettlement",
    "EntrySettlementContext",
    "ExitSettlementService",
    "ExitSettlement",
    "ExitSettlementContext",
    "FeeDetail",
    "FeeResolver",
    "FeeSchedule",
    "executed_fee",
    "executed_notional",
    "WalletEvent",
    "LockedWalletLedger",
    "WalletLedger",
    "WalletState",
    "project_wallet",
    "project_wallet_from_events",
    "wallet_can_apply",
    "wallet_can_apply_exit",
    "wallet_required_reservation",
    "wallet_required_reservation_details",
    "BaseWalletGateway",
    "SharedWalletGateway",
    "WalletGateway",
    "InstrumentContract",
    "ExecutionConstraintsContract",
    "ExecutionCapabilities",
    "ExecutionFeeContract",
    "RiskConfigContract",
    "CollateralModel",
    "SimpleCollateralModel",
    "SeriesExecutionProfile",
    "normalize_execution_semantics",
    "normalize_runtime_instrument_type",
    "compile_series_execution_profile",
    "DecisionAcceptedContext",
    "DecisionRejectedContext",
    "SCHEMA_VERSION",
    "SignalEmittedContext",
    "EntryFilledContext",
    "ExitKind",
    "ExitFilledContext",
    "ReasonCode",
    "RuntimeBar",
    "RuntimeErrorContext",
    "RuntimeEvent",
    "RuntimeEventCategory",
    "RuntimeStatusContext",
    "RuntimeEventName",
    "WalletDelta",
    "WalletDepositedContext",
    "WalletInitializedContext",
    "build_correlation_id",
    "coerce_reason_code",
    "decision_trace_entry_from_runtime_event",
    "format_correlation_bar_ts",
    "new_runtime_event",
    "normalize_utc_datetime",
    "runtime_event_from_dict",
]
