"""Core execution and domain logic for bot runtime."""

from .domain import (
    CandleSnapshot,
    Candle,
    EntryFill,
    EntryFillResult,
    EntryRequest,
    EntryValidation,
    LadderPosition,
    LadderRiskEngine,
    Leg,
    StrategySignal,
)
from .execution import (
    FillRejection,
    FillResult,
    SpotExecutionConstraints,
    SpotExecutionModel,
    DerivativesExecutionConstraints,
    DerivativesExecutionModel,
)
from .execution_adapter import ExecutionAdapter, SpotExecutionAdapter, DerivativesExecutionAdapter
from .execution_intent import ExecutionIntent, ExecutionOutcome, LimitParams
from .execution_model import ExecutionModel
from .execution_runtime import DeterministicExecutionModel
from .entry_execution import EntryExecutionCoordinator, PendingEntry
from .entry_settlement import EntrySettlement, EntrySettlementContext, EntrySettlementService
from .exit_settlement import ExitSettlement, ExitSettlementContext, ExitSettlementService
from .fees import FeeDetail, FeeResolver, FeeSchedule
from .wallet import (
    LockedWalletLedger,
    WalletEvent,
    WalletLedger,
    WalletState,
    project_wallet,
    project_wallet_from_events,
    wallet_can_apply,
    wallet_required_reservation,
)
from .wallet_gateway import BaseWalletGateway, SharedWalletGateway, WalletGateway
from .execution_profile import (
    InstrumentContract,
    ExecutionConstraintsContract,
    ExecutionCapabilities,
    RiskConfigContract,
    CollateralModel,
    SimpleCollateralModel,
    SeriesExecutionProfile,
    normalize_runtime_instrument_type,
    compile_series_execution_profile,
    compile_runtime_profile_or_error,
)
from .runtime_events import (
    SCHEMA_VERSION,
    ExitKind,
    ReasonCode,
    RuntimeEvent,
    RuntimeEventCategory,
    RuntimeEventName,
    build_correlation_id,
    coerce_reason_code,
    format_correlation_bar_ts,
    new_runtime_event,
    normalize_utc_datetime,
    runtime_event_from_dict,
)

__all__ = [
    "Candle",
    "CandleSnapshot",
    "EntryFill",
    "EntryFillResult",
    "EntryRequest",
    "EntryValidation",
    "LadderPosition",
    "LadderRiskEngine",
    "Leg",
    "StrategySignal",
    "FillRejection",
    "FillResult",
    "SpotExecutionConstraints",
    "SpotExecutionModel",
    "DerivativesExecutionConstraints",
    "DerivativesExecutionModel",
    "ExecutionAdapter",
    "SpotExecutionAdapter",
    "DerivativesExecutionAdapter",
    "ExecutionIntent",
    "ExecutionOutcome",
    "LimitParams",
    "ExecutionModel",
    "DeterministicExecutionModel",
    "EntryExecutionCoordinator",
    "PendingEntry",
    "EntrySettlementService",
    "EntrySettlement",
    "EntrySettlementContext",
    "ExitSettlementService",
    "ExitSettlement",
    "ExitSettlementContext",
    "FeeDetail",
    "FeeResolver",
    "FeeSchedule",
    "WalletEvent",
    "LockedWalletLedger",
    "WalletLedger",
    "WalletState",
    "project_wallet",
    "project_wallet_from_events",
    "wallet_can_apply",
    "wallet_required_reservation",
    "BaseWalletGateway",
    "SharedWalletGateway",
    "WalletGateway",
    "InstrumentContract",
    "ExecutionConstraintsContract",
    "ExecutionCapabilities",
    "RiskConfigContract",
    "CollateralModel",
    "SimpleCollateralModel",
    "SeriesExecutionProfile",
    "normalize_runtime_instrument_type",
    "compile_series_execution_profile",
    "compile_runtime_profile_or_error",
    "SCHEMA_VERSION",
    "ExitKind",
    "ReasonCode",
    "RuntimeEvent",
    "RuntimeEventCategory",
    "RuntimeEventName",
    "build_correlation_id",
    "coerce_reason_code",
    "format_correlation_bar_ts",
    "new_runtime_event",
    "normalize_utc_datetime",
    "runtime_event_from_dict",
]
