"""Utilities for building signal overlays for chart plotting."""

from __future__ import annotations

import logging
from typing import Any, Callable, Dict, Iterable, List, Mapping, MutableMapping, Sequence

import pandas as pd

from signals.base import BaseSignal

logger = logging.getLogger(__name__)

Overlay = Dict[str, Any]
OverlayAdapter = Callable[..., List[Overlay]]


class OverlayAdapterRegistry(dict):
    """Registry for overlay adapter callables."""

    def register(self, name: str, func: OverlayAdapter) -> OverlayAdapter:
        logger.debug("Registering overlay adapter '%s'", name)
        self[name] = func
        return func


overlay_adapters: MutableMapping[str, OverlayAdapter] = OverlayAdapterRegistry()


def register_overlay_adapter(name: str) -> Callable[[OverlayAdapter], OverlayAdapter]:
    """Decorator to register an overlay adapter function."""

    def decorator(func: OverlayAdapter) -> OverlayAdapter:
        return overlay_adapters.register(name, func)

    return decorator


@register_overlay_adapter("pivot")
def pivot_signals_to_overlays(
    signals: Sequence[BaseSignal],
    *,
    plot_df: pd.DataFrame,
    pivot_breakout_confirmation_bars: int | None = None,
    **_: Any,
) -> List[Overlay]:
    """Convert pivot signals into overlay configuration objects.

    Parameters
    ----------
    signals:
        Sequence of :class:`BaseSignal` instances for the pivot rule.
    plot_df:
        Dataframe used for plotting. Required for API compatibility but not
        used directly by the simplified implementation.
    pivot_breakout_confirmation_bars:
        Optional rule configuration value indicating the minimum confirmation
        bars required for a breakout.  The adapter tolerates the value even if
        it is not used so that the caller can forward rule configuration
        without raising ``TypeError``.

    Returns
    -------
    list of dict
        Overlay definitions derived from the provided signals.
    """

    if not signals:
        return []

    confirmation_threshold = pivot_breakout_confirmation_bars

    overlays: List[Overlay] = []
    for signal in signals:
        metadata = signal.metadata or {}

        if (
            confirmation_threshold is not None
            and metadata.get("confirmation_bars") is not None
            and metadata.get("confirmation_bars") < confirmation_threshold
        ):
            logger.debug(
                "Skipping signal at %s due to confirmation threshold (%s < %s)",
                signal.time,
                metadata.get("confirmation_bars"),
                confirmation_threshold,
            )
            continue

        overlays.append(
            {
                "kind": "marker",
                "time": signal.time,
                "price": metadata.get("price"),
                "direction": metadata.get("direction"),
                "label": metadata.get("label", signal.type.capitalize()),
            }
        )

    return overlays


def build_signal_overlays(
    signals_by_rule: Mapping[str, Sequence[BaseSignal]],
    overlay_rules: Iterable[Mapping[str, Any]],
    *,
    plot_df: pd.DataFrame,
) -> List[Overlay]:
    """Build overlays for configured signal rules.

    Parameters
    ----------
    signals_by_rule:
        Mapping from rule identifiers to the signals generated by those rules.
    overlay_rules:
        Iterable of configuration dictionaries describing which adapter to use
        and any additional keyword arguments to forward to the adapter.
    plot_df:
        DataFrame with plotting data required by the adapters.

    Returns
    -------
    list of dict
        Combined overlays produced by the configured adapters.
    """

    overlays: List[Overlay] = []

    for rule in overlay_rules:
        adapter_name = rule.get("adapter")
        if not adapter_name:
            logger.debug("Skipping overlay rule without adapter: %s", rule)
            continue

        adapter = overlay_adapters.get(adapter_name)
        if adapter is None:
            logger.warning("No overlay adapter registered under '%s'", adapter_name)
            continue

        rule_key = rule.get("rule") or adapter_name
        rule_signals = signals_by_rule.get(rule_key, [])
        adapter_kwargs = dict(rule.get("config", {}))

        try:
            overlays.extend(
                adapter(
                    rule_signals,
                    plot_df=plot_df,
                    **adapter_kwargs,
                )
            )
        except TypeError:
            logger.exception("Overlay adapter '%s' rejected config %s", adapter_name, adapter_kwargs)
            raise

    return overlays
