"""Immutable scientific-protocol contracts for offline quantitative research."""

from .contracts import (
    BLINDNESS_SCHEMA_VERSION,
    CANDIDATE_SCHEMA_VERSION,
    PROTOCOL_SCHEMA_VERSION,
    SCIENTIFIC_EVIDENCE_SCHEMA_VERSION,
    BlindnessClass,
    CandidateSnapshot,
    DatasetAssignment,
    DatasetRole,
    LeakagePolicy,
    ScientificEvidence,
    ScientificQualityAssessment,
    ScientificQualityClass,
    ScientificProtocol,
    SearchBudget,
    WalkForwardFold,
    WalkForwardPlan,
    adjusted_p_values,
    classify_scientific_quality,
    deterministic_block_bootstrap_ci,
)

__all__ = [
    "BLINDNESS_SCHEMA_VERSION",
    "CANDIDATE_SCHEMA_VERSION",
    "PROTOCOL_SCHEMA_VERSION",
    "SCIENTIFIC_EVIDENCE_SCHEMA_VERSION",
    "BlindnessClass",
    "CandidateSnapshot",
    "DatasetAssignment",
    "DatasetRole",
    "LeakagePolicy",
    "ScientificEvidence",
    "ScientificProtocol",
    "ScientificQualityAssessment",
    "ScientificQualityClass",
    "SearchBudget",
    "WalkForwardFold",
    "WalkForwardPlan",
    "adjusted_p_values",
    "classify_scientific_quality",
    "deterministic_block_bootstrap_ci",
]
