
services:
  test:
    build:
      context: ..
      dockerfile: docker/test/Dockerfile
    volumes:
      - ../:/app
    working_dir: /app
    env_file:
      - ../secrets.env
      - ../.env.test
    depends_on:
      timescaledb:
        condition: service_healthy
    command: ["bash","-lc","export PG_DSN=postgresql+psycopg2://$$POSTGRES_USER:$$POSTGRES_PASSWORD@timescaledb:5432/$$POSTGRES_DB && python -m pip install --upgrade pip && bash /app/scripts/wait-for-db.sh pytest --cov=src --cov-report=term --cov-report=xml"]



  timescaledb:
    image: timescale/timescaledb:latest-pg14
    env_file:
      - ../secrets.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\""]
      interval: 5s
      timeout: 3s
      retries: 10
