"""Regime indicator manifest."""

from __future__ import annotations

from indicators.manifest import (
    IndicatorDependency,
    IndicatorManifest,
    IndicatorOutput,
    IndicatorOverlay,
    IndicatorParam,
)


MANIFEST = IndicatorManifest(
    type="regime",
    version="v1",
    label="Regime",
    description="Walk-forward market regime classification built from candle stats.",
    color_mode="palette",
    params=(
        IndicatorParam(
            key="min_confidence",
            type="float",
            label="Minimum Confidence",
            description="Minimum confidence required for regime acceptance.",
            default=0.60,
        ),
        IndicatorParam(
            key="structure_min_confidence",
            type="float",
            label="Structure Minimum Confidence",
            description="Minimum confidence required for structure classification.",
            default=0.45,
        ),
        IndicatorParam(
            key="structure_confirm_bars",
            type="int",
            label="Structure Confirm Bars",
            description="Bars required to confirm structure changes.",
            default=3,
            advanced=True,
            group="confirmation",
        ),
        IndicatorParam(
            key="volatility_confirm_bars",
            type="int",
            label="Volatility Confirm Bars",
            description="Bars required to confirm volatility changes.",
            default=4,
            advanced=True,
            group="confirmation",
        ),
        IndicatorParam(
            key="liquidity_confirm_bars",
            type="int",
            label="Liquidity Confirm Bars",
            description="Bars required to confirm liquidity changes.",
            default=3,
            advanced=True,
            group="confirmation",
        ),
        IndicatorParam(
            key="expansion_confirm_bars",
            type="int",
            label="Expansion Confirm Bars",
            description="Bars required to confirm expansion changes.",
            default=3,
            advanced=True,
            group="confirmation",
        ),
        IndicatorParam(
            key="smoothing_alpha",
            type="float",
            label="Smoothing Alpha",
            description="Smoothing factor applied before stabilizing regime transitions.",
            default=0.25,
            advanced=True,
        ),
    ),
    outputs=(
        IndicatorOutput(
            name="market_regime",
            type="context",
            label="Market Regime",
            state_keys=(
                "trend_up",
                "trend_down",
                "range",
                "transition_up",
                "transition_down",
                "transition_neutral",
                "unknown",
            ),
            fields=(
                "regime_key",
                "committed_state",
                "context_regime_state",
                "context_regime_direction",
                "actionable_state",
                "trend_direction",
                "structure_confidence",
                "score_margin",
                "volatility_state",
                "liquidity_state",
                "expansion_state",
                "bars_in_regime",
                "age_since_known_bars",
                "recent_switch_count",
                "known_at_epoch",
                "is_known",
                "is_mature",
                "is_trustworthy",
                "trust_score",
                "context_bars_in_regime",
                "context_age_since_known_bars",
                "context_recent_switch_count",
                "context_known_at_epoch",
                "context_is_known",
                "context_is_mature",
                "context_is_trustworthy",
                "context_trust_score",
                "candidate_state",
                "candidate_count",
                "current_confirm_required",
            ),
        ),
        IndicatorOutput(
            name="regime_metrics",
            type="metric",
            label="Regime Metrics",
            fields=(
                "trend_score",
                "range_score",
                "transition_score",
                "structure_confidence",
                "score_margin",
                "winner_score",
                "directional_efficiency",
                "slope",
                "slope_stability",
                "range_position",
                "range_contraction",
                "overlap_pct",
                "atr_ratio",
                "atr_zscore",
                "tr_pct",
                "atr_slope",
                "volume_zscore",
                "volume_vs_median",
                "trend_direction_value",
                "bars_in_regime",
                "age_since_known_bars",
                "recent_switch_count",
                "structure_switch_count",
                "trust_score",
                "is_known",
                "is_mature",
                "is_trustworthy",
                "context_bars_in_regime",
                "context_age_since_known_bars",
                "context_recent_switch_count",
                "context_switch_count",
                "context_trust_score",
                "context_is_known",
                "context_is_mature",
                "context_is_trustworthy",
            ),
        ),
    ),
    overlays=(
        IndicatorOverlay(
            name="regime",
            overlay_type="regime_overlay",
            label="Regime Overlay",
            description="Canonical regime structure blocks with known-at boundaries.",
        ),
        IndicatorOverlay(
            name="regime_markers",
            overlay_type="regime_markers",
            label="Regime Markers",
            description="Confirmed regime change markers rendered at block known-at bars.",
        ),
    ),
    dependencies=(
        IndicatorDependency(
            indicator_type="candle_stats",
            output_name="candle_stats",
            label="Candle Stats",
            description="Regime classification requires candle stats runtime metrics.",
        ),
    ),
)

__all__ = ["MANIFEST"]
