"""Strategy service package exposing a thin facade and helper modules."""

from strategies import evaluator, markers

from . import persistence
from .facade import (
    RuleCondition,
    StrategyDefinition,
    StrategyRegistry,
    StrategyRule,
    create_rule,
    create_rule_filter,
    create_strategy,
    create_strategy_filter,
    delete_rule,
    delete_rule_filter,
    delete_strategy,
    delete_strategy_filter,
    delete_symbol_preset_service,
    generate_strategy_signals,
    get_strategy,
    list_atm_templates,
    list_rule_filters,
    list_strategies,
    list_strategy_filters,
    list_symbol_presets_service,
    register_indicator,
    save_atm_template,
    save_symbol_preset_service,
    unregister_indicator,
    update_rule,
    update_rule_filter,
    update_strategy,
    update_strategy_filter,
)

__all__ = [
    "RuleCondition",
    "StrategyDefinition",
    "StrategyRegistry",
    "StrategyRule",
    "create_rule",
    "create_rule_filter",
    "create_strategy",
    "create_strategy_filter",
    "delete_rule",
    "delete_rule_filter",
    "delete_strategy",
    "delete_strategy_filter",
    "delete_symbol_preset_service",
    "evaluator",
    "generate_strategy_signals",
    "get_strategy",
    "list_atm_templates",
    "list_rule_filters",
    "list_strategies",
    "list_strategy_filters",
    "list_symbol_presets_service",
    "markers",
    "persistence",
    "register_indicator",
    "save_atm_template",
    "save_symbol_preset_service",
    "unregister_indicator",
    "update_rule",
    "update_rule_filter",
    "update_strategy",
    "update_strategy_filter",
]
