import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const srcRoot = path.join(here, '..', 'src')
const source = (relative) => readFileSync(path.join(srcRoot, relative), 'utf8')

test('Overview is a compact dashboard rather than a numbered operational report', () => {
  const overview = source(path.join('v2', 'rooms', 'OverviewRoom.jsx'))
  assert.match(overview, /qt2-summary-grid/)
  assert.match(overview, /attentionItems\.slice\(0, 3\)/)
  assert.match(overview, /const attentionTotal = Number\(fleet\.attention_count \|\| 0\)/)
  assert.match(overview, /hiddenAttentionCount/)
  assert.match(overview, /ComponentAvailability issues={attentionIssues}/)
  assert.match(overview, /Partial evidence/)
  assert.doesNotMatch(overview, /operationsErrors\.join|researchFeed\.errors\.join/)
  assert.doesNotMatch(overview, /qt2-step|function MarketPosture|function RecentOutcomes/)
  assert.match(overview, /RoomLoadingFrame/)
  assert.match(overview, /operationsLoading && !projectedRuns\.length && !collectorFeed\.providers\.length/)
  const app = source(path.join('v2', 'AppV2.jsx'))
  assert.match(app, /label === 'Overview'[\s\S]*RoomLoadingFrame/)
})

test('Operations uses three task domains, canonical collector operations, and cursor-backed run history', () => {
  const operations = source(path.join('v2', 'rooms', 'FleetRoom.jsx'))
  const console = source(path.join('features', 'collectors', 'CollectorFleetConsole.jsx'))
  assert.match(operations, /id: \x27market\x27/)
  assert.match(operations, /CollectorFleetConsole/)
  assert.match(console, /Provider first/)
  assert.match(console, /All collectors/)
  assert.match(console, /Attention only/)
  assert.match(console, /useCollectorPage/)
  assert.doesNotMatch(console, /Live collector flow|Fact store/)
  assert.match(operations, /runInventory\.loadMore/)
  assert.match(operations, /BotLens unavailable/)
  assert.match(operations, /Copy rerun command/)
  assert.match(operations, /Test window/)
  assert.match(operations, /displayed end boundary/)
  assert.doesNotMatch(operations, /id: \x27collectors\x27|id: \x27market-data\x27/)
  assert.doesNotMatch(operations, /errors\.map/)
})

test('operator errors preserve technical details behind readable copy', () => {
  const notice = source(path.join('v2', 'components', 'OperatorErrorNotice.jsx'))
  assert.match(notice, /Normalization evidence failed an integrity check/)
  assert.match(notice, /Technical details/)
  assert.match(notice, /Copy details/)
  assert.match(notice, /navigator\.clipboard\.writeText/)
})

test('historical BotLens loading is bounded and bidirectional pan retrieval uses current callbacks', () => {
  const controller = source(path.join('features', 'bots', 'botlens', 'hooks', 'useBotLensController.js'))
  const content = source(path.join('features', 'bots', 'botlens', 'BotLensContent.jsx'))
  const viewport = source(path.join('components', 'bots', 'hooks', 'useViewportController.js'))
  const chart = source(path.join('components', 'bots', 'BotLensChart.jsx'))
  const markerManager = source(path.join('components', 'bots', 'hooks', 'useMarkerManager.js'))
  assert.match(controller, /BOTLENS_EXACT_BOOTSTRAP_TIMEOUT_MS = 30_000/)
  assert.match(controller, /fetchExactRunBootstrapBeforeDeadline\(runId, exactBootstrapDeadline, bootstrapController\.signal\)/)
  assert.match(controller, /Historical BotLens replay did not become ready within 30 seconds/)
  assert.match(controller, /const currentState = stateRef\.current/)
  assert.match(controller, /chartHistoryStatus: currentChartHistoryStatus/)
  assert.doesNotMatch(controller, /\n\s+chartCandles,\n\s+chartHistoryStatus,\n\s+datasetId,/)
  assert.match(controller, /BOTLENS_DURABLE_EVIDENCE_STAGES/)
  assert.match(controller, /beginChartRequest/)
  assert.match(content, /Diagnostic evidence/)
  assert.match(content, /Unavailable in persisted evidence/)
  assert.match(content, /createPortal\(lens, document\.body\)/)
  assert.match(content, /layout: 'compact'/)
  assert.match(content, /VirtualRows/)
  assert.match(content, /JSON\.stringify\(payload, null, 2\)/)
  assert.match(viewport, /nearHistoryTriggeredRef/)
  assert.match(viewport, /onNearHistoryStartRef\.current = onNearHistoryStart/)
  assert.match(viewport, /onNearHistoryEndRef\.current = onNearHistoryEnd/)
  assert.match(viewport, /onNearHistoryStartRef\.current\?\.\(\)/)
  assert.match(viewport, /onNearHistoryEndRef\.current\?\.\(\)/)
  assert.match(markerManager, /zOrder: 'aboveSeries'/)
  assert.match(markerManager, /if \(force \|\| signature !== lastSignatureRef\.current\)/)
  assert.match(chart, /refreshMarkers\(\{ force: true \}\)/)
  assert.doesNotMatch(source(path.join('features', 'bots', 'botlens', 'components', 'ChartPanel.jsx')), /Load earlier/)
})
