apiVersion: 1

deleteRules:
  - orgId: 1
    uid: qt-database-unavailable
  - orgId: 1
    uid: qt-collector-reconnect-storm

deleteContactPoints:
  - orgId: 1
    uid: qt-operator-email

resetPolicies:
  - 1
