symbol: AAPL
history_days: 365
ingest_intervals: ["60m"]
exec_days: 120
higher_days: 365
min_va_cluster: 3
vwap_k: 2.0
atr_factor: 0.15
entry_threshold: 0.8
stop_loss: 1.0
take_profit: 2.0
output_dir: strategy2