"""Cohesive storage repositories grouped by model domain."""

from ._shared import _coerce_float, _coerce_int, _parse_optional_timestamp, _utcnow
from .atm import get_atm_template, load_atm_templates, upsert_atm_template
from .bots import (
    clear_bot_runner,
    delete_bot,
    find_orphaned_bots,
    get_bot,
    load_bots,
    mark_bot_crashed,
    update_bot_heartbeat,
    update_bot_run_artifact,
    upsert_bot,
)
from .lifecycle import (
    get_bot_run_lifecycle,
    get_latest_bot_run_lifecycle,
    list_bot_run_lifecycle_events,
    record_bot_run_lifecycle_checkpoint,
)
from .indicators import (
    delete_indicator,
    get_indicator,
    load_indicators,
    strategies_for_indicator,
    upsert_indicator,
)
from .instruments import (
    delete_instrument,
    find_instrument,
    get_instrument,
    list_strategy_instrument_links,
    list_strategy_instrument_symbols,
    load_instruments,
    upsert_instrument,
)
from .presets import delete_symbol_preset, list_symbol_presets, upsert_symbol_preset
from .runs import get_bot_run, list_bot_runs, upsert_bot_run
from .runtime_events import (
    get_latest_bot_run_view_state,
    get_latest_bot_runtime_event,
    get_latest_bot_runtime_run_id,
    list_bot_run_view_states,
    list_bot_runtime_events,
    record_bot_run_step,
    record_bot_run_steps_batch,
    record_bot_runtime_event,
    record_bot_runtime_events_batch,
    upsert_bot_run_view_state,
    update_bot_runtime_status,
)
from .strategies import (
    delete_strategy_variant,
    delete_orphan_strategy_instrument_links,
    delete_strategy,
    delete_strategy_indicator,
    delete_strategy_instrument,
    delete_strategy_rule,
    ensure_default_strategy_variant,
    get_strategy_variant,
    list_strategy_variants,
    load_strategies,
    upsert_strategy,
    upsert_strategy_indicator,
    upsert_strategy_instrument,
    upsert_strategy_rule,
    upsert_strategy_variant,
)
from .trades import (
    list_bot_trade_events_for_trades,
    list_bot_trades_for_run,
    record_bot_trade,
    record_bot_trade_event,
)

__all__ = [
    "_coerce_float",
    "_coerce_int",
    "_parse_optional_timestamp",
    "_utcnow",
    "clear_bot_runner",
    "delete_bot",
    "delete_indicator",
    "delete_instrument",
    "delete_orphan_strategy_instrument_links",
    "delete_strategy",
    "delete_strategy_indicator",
    "delete_strategy_instrument",
    "delete_strategy_rule",
    "delete_strategy_variant",
    "delete_symbol_preset",
    "ensure_default_strategy_variant",
    "find_instrument",
    "find_orphaned_bots",
    "get_atm_template",
    "get_bot",
    "get_bot_run_lifecycle",
    "get_bot_run",
    "get_indicator",
    "get_instrument",
    "get_latest_bot_run_lifecycle",
    "get_strategy_variant",
    "get_latest_bot_run_view_state",
    "get_latest_bot_runtime_event",
    "get_latest_bot_runtime_run_id",
    "list_bot_run_view_states",
    "list_bot_run_lifecycle_events",
    "list_bot_runs",
    "list_bot_runtime_events",
    "list_bot_trade_events_for_trades",
    "list_bot_trades_for_run",
    "list_strategy_variants",
    "list_strategy_instrument_links",
    "list_strategy_instrument_symbols",
    "list_symbol_presets",
    "load_atm_templates",
    "load_bots",
    "load_indicators",
    "load_instruments",
    "load_strategies",
    "mark_bot_crashed",
    "record_bot_run_step",
    "record_bot_run_steps_batch",
    "record_bot_run_lifecycle_checkpoint",
    "record_bot_runtime_event",
    "record_bot_runtime_events_batch",
    "upsert_bot_run_view_state",
    "record_bot_trade",
    "record_bot_trade_event",
    "strategies_for_indicator",
    "update_bot_heartbeat",
    "update_bot_run_artifact",
    "update_bot_runtime_status",
    "upsert_atm_template",
    "upsert_bot",
    "upsert_bot_run",
    "upsert_indicator",
    "upsert_instrument",
    "upsert_strategy",
    "upsert_strategy_indicator",
    "upsert_strategy_instrument",
    "upsert_strategy_rule",
    "upsert_strategy_variant",
    "upsert_symbol_preset",
]
