"""Canonical market-data contracts and feed boundaries."""

from .store import FrozenDataset, IngestionOutcome, MarketDataStore
from .contracts import (
    CANDLE_FACT_TYPE,
    CANDLE_FACT_VERSION,
    FUNDING_RATE_FACT_TYPE,
    FUNDING_RATE_FACT_VERSION,
    OPEN_INTEREST_FACT_TYPE,
    OPEN_INTEREST_FACT_VERSION,
    CandleFact,
    CandleRecord,
    DatasetSeriesRequest,
    FundingRateFact,
    FundingRateRecord,
    InstrumentRole,
    MarketDataAlignment,
    MarketDataRequirement,
    MarketDataWindow,
    OpenInterestFact,
    OpenInterestRecord,
    SourceIdentity,
    build_candle_material_hash,
    build_funding_rate_material_hash,
    build_open_interest_material_hash,
    build_provenance_hash,
    build_quality_hash,
)
from .requirements import (
    BoundMarketDataContext,
    InstrumentResolutionContext,
    MarketDataPlanResolver,
    ResolvedMarketDataPlan,
    UnavailableMarketData,
)

__all__ = [
    "FrozenDataset",
    "IngestionOutcome",
    "MarketDataStore",
    "CANDLE_FACT_TYPE",
    "CANDLE_FACT_VERSION",
    "FUNDING_RATE_FACT_TYPE",
    "FUNDING_RATE_FACT_VERSION",
    "OPEN_INTEREST_FACT_TYPE",
    "OPEN_INTEREST_FACT_VERSION",
    "CandleFact",
    "CandleRecord",
    "DatasetSeriesRequest",
    "FundingRateFact",
    "FundingRateRecord",
    "InstrumentRole",
    "MarketDataAlignment",
    "MarketDataRequirement",
    "MarketDataWindow",
    "OpenInterestFact",
    "OpenInterestRecord",
    "SourceIdentity",
    "build_candle_material_hash",
    "build_funding_rate_material_hash",
    "build_open_interest_material_hash",
    "build_provenance_hash",
    "build_quality_hash",
    "BoundMarketDataContext",
    "InstrumentResolutionContext",
    "MarketDataPlanResolver",
    "ResolvedMarketDataPlan",
    "UnavailableMarketData",
]
