"""Bot runtime engine (core domain + execution primitives)."""

from .adapters import BacktestAdapter, LiveAdapter, PaperAdapter
from .core import (
    Candle,
    LadderPosition,
    LadderRiskEngine,
    Leg,
    StrategySignal,
    FillRejection,
    FillResult,
    SpotExecutionConstraints,
    SpotExecutionModel,
    ExecutionAdapter,
    SpotExecutionAdapter,
    WalletEvent,
    WalletLedger,
    WalletState,
    project_wallet,
    wallet_can_apply,
    LedgerWalletGateway,
    WalletGateway,
)

__all__ = [
    "Candle",
    "LadderPosition",
    "LadderRiskEngine",
    "Leg",
    "StrategySignal",
    "FillRejection",
    "FillResult",
    "SpotExecutionConstraints",
    "SpotExecutionModel",
    "ExecutionAdapter",
    "SpotExecutionAdapter",
    "BacktestAdapter",
    "PaperAdapter",
    "LiveAdapter",
    "WalletEvent",
    "WalletLedger",
    "WalletState",
    "project_wallet",
    "wallet_can_apply",
    "LedgerWalletGateway",
    "WalletGateway",
]
